package com.dwh.movieapp.navigation

object Screens {
    //Splash
    const val SPLASH_SCREEN = "SPLASH_SCREEN"
    //Main
    const val HOME_SCREEN = "HOME_SCREEN"
    //Movies
    const val POPULAR_MOVIES_SCREEN = "POPULAR_MOVIES_SCREEN"
    const val TOP_RATED_MOVIES_SCREEN = "TOP_RATED_MOVIES_SCREEN"
    const val TOP_RATED_MOVIES_DETAILS_SCREEN = "TOP_RATED_MOVIES_DETAILS_SCREEN"
    const val MOVIES_DETAILS_SCREEN = "MOVIES_DETAILS_SCREEN"
    //Series
    const val POPULAR_SERIES_SCREEN = "POPULAR_SERIES_SCREEN"
    const val TOP_RATED_SERIES_SCREEN = "TOP_RATED_SERIES_SCREEN"
    const val TOP_RATED_SERIES_DETAILS_SCREEN = "TOP_RATED_SERIES_DETAILS_SCREEN"
    const val SERIES_DETAILS_SCREEN = "SERIES_DETAILS_SCREEN"
}